### ISSUE TITLE
Lock-up

### ISSUE THREAD

**Issue by rmchale** [iiz00/obsidian-daily-note-outline#5] opened 2022-12-07 21:21 UTC
Does this plugin cause anyone else's obsidian to lock-up?

**Comment by iiz00** [comment] 2022-12-08 03:41
Was this plugin irrelevant? If so, I will close the issue. If you still have problems, please let me know the details.

**Comment by iiz00** [comment] 2022-12-08 08:46
Oh, sorry about that. What is actually happening with "lock-up"? I am also using v1.1 of the insider build and have not experienced any problems in my environment.
In v1.1, there is a reported compatibility problem with the Multi-Column Markdown plugin (see https://github.com/ckRobinson/multi-column-markdown/issues/55). In that case, an error occurs while loading Obsidian and it fails to start up. Is this the same situation? Or does keyboard input stop working in the middle of a sentence, or does Obsidian itself freeze during any operation? 
If possible, could you try uninstalling and reinstalling?
I would be grateful if you could provide me with more details.

**Comment by iiz00** [comment] 2022-12-08 16:02
Thank you for your information! However, I cannot reproduce this in my environment at the moment, so I need to isolate the problem. I would appreciate it if you could help me isolate the problem when you have time. Sorry for the long list. 

- If you see an error in the console, please let me know.
- At what point in time the symptoms appear: does it slow down immediately after displaying the outline view? Does the symptom occur when you perform any operation, such as editing any of daily notes? Or if the plugin is enabled, is it slow even when the view is not open?
- Are outlines renderd or not?
- Can you click on icons (arrows, home, refresh, settings) at the top of the view? Are they inoperable? Also, do the symptoms persist when you click on the left-pointing arrow to view past daily notes?

- I would need to look into this more closely, but at a cursory glance, it does not appear that there are any API changes in v1.1 that might be related to this issue, and I think it is possible that it is failing to process any of the daily notes that were created around December 6, when v1.1 was released.
- Can you try disabling the inline preview and tooltip preview introduced in v0.3.0 and see if that changes the behavior?
- Also, could you try to hide all outline elements (heading, link, tag, list items) in the settings and see if that changes the behavior?
- If you don't mind, could you tell me a list of plugins you have enabled? I would like to try activating the same plugins and see if it has any impact.

**Comment by hsiktas** [comment] 2023-01-10 21:49
I think I am also seeing this on mobile insiders. With this plugin enabled, I get hangs for multiple seconds and the app crashes and restarts frequently.
On the desktop insider builds I see no issues. 🤷‍♂️

**Comment by iiz00** [comment] 2023-01-11 04:37
Yes, I have confirmed the same symptom with iOS beta v1.4.2 (though I think it was ok in previous versions...). I will look into the cause. Sorry for the inconvenience.

**Comment by iiz00** [comment] 2023-01-13 17:55
I think v0.5.0 fixes the overload problem (at least for what I observed in the iOS version). I would appreciate it if you could update and let me know if the problem persists.

**Comment by hsiktas** [comment] 2023-01-14 18:45
Yes, I updated and can't reproduce the issue anymore :)

**Comment by iiz00** [comment] 2023-01-15 08:56
I am glad to hear that! I will close this issue, but if you have any more problems, please let me know.

**Closed** 2023-01-15 08:57 UTC
